package com.example.payload;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * Auto-generated payload class for CloudEvent message data.
 * Generated by BAMOE - do not edit manually.
 */
@RegisterForReflection
public class Event0m799toPayload {

    private String userId;

    public Event0m799toPayload() {
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
