package com.example.payload;

import jakarta.enterprise.context.ApplicationScoped;
import org.kie.api.event.process.ProcessNodeLeftEvent;
import org.kie.kogito.internal.process.event.DefaultKogitoProcessEventListener;
import org.kie.kogito.internal.process.runtime.KogitoProcessInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

/**
 * Auto-generated listener that extracts payload fields from message events
 * and sets them as process variables.
 *
 * Uses afterNodeLeft for ALL message events (including start events).
 * This fires AFTER each node completes and dataOutputAssociations are processed,
 * ensuring message data is available in process variables.
 *
 * Handles both typed payload classes and raw Map payloads.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class MessagePayloadExtractor extends DefaultKogitoProcessEventListener {

    private static final Logger LOG = LoggerFactory.getLogger(MessagePayloadExtractor.class);

    /**
     * Handle ALL message events (start events, catch events, boundary events, receive tasks).
     * This fires AFTER each node completes and dataOutputAssociations are processed,
     * so the message variable is available.
     */
    @Override
    public void afterNodeLeft(ProcessNodeLeftEvent event) {
        String nodeId = event.getNodeInstance().getNodeId().toExternalFormat();
        LOG.debug("afterNodeLeft fired for nodeId: {}", nodeId);

        if (event.getProcessInstance() instanceof KogitoProcessInstance) {
            KogitoProcessInstance kpi = (KogitoProcessInstance) event.getProcessInstance();
            Map<String, Object> variables = kpi.getVariables();
            LOG.debug("Process variables: {}", variables.keySet());

            if ("Event_1nyzw2y".equals(nodeId)) {
                LOG.info("Processing message event Event_1nyzw2y");
                Object messageData = variables.get("message_Event_1nyzw2y");
                LOG.debug("messageData for Event_1nyzw2y: {} (type: {})", messageData, messageData != null ? messageData.getClass().getName() : "null");
                if (messageData != null) {
                    if (messageData instanceof com.example.payload.RenewalsPayload) {
                        // Typed payload - BPMN has correct structureRef
                        LOG.debug("Using typed payload extraction");
                        com.example.payload.RenewalsPayload typedPayload = (com.example.payload.RenewalsPayload) messageData;
                    kpi.setVariable("userId", typedPayload.getUserId());
                    LOG.info("Set process variable userId = {} (from typed payload)", typedPayload.getUserId());
                    } else if (messageData instanceof java.util.Map) {
                        // Raw Map payload - navigate structure as specified in expressions
                        LOG.debug("Using raw Map payload extraction");
                        @SuppressWarnings("unchecked")
                        java.util.Map<String, Object> rawMap = (java.util.Map<String, Object>) messageData;
                        LOG.debug("rawMap contents: {}", rawMap);
                    Object userIdValue = (rawMap.containsKey("specversion") && rawMap.containsKey("data")
                        ? (getNestedMap(rawMap, "data") != null ? getNestedMap(rawMap, "data").get("userId") : null)
                        : rawMap.get("userId"));
                    LOG.debug("Extracted userId: {}", userIdValue);
                    if (userIdValue != null) {
                        kpi.setVariable("userId", userIdValue);
                        LOG.info("Set process variable userId = {}", userIdValue);
                    }
                    } else {
                        LOG.warn("Unexpected messageData type: {}", messageData.getClass().getName());
                    }
                } else {
                    LOG.warn("messageData is null for event Event_1nyzw2y");
                }
            }
        }
    }

    /**
     * Safely get a nested map from a parent map
     */
    @SuppressWarnings("unchecked")
    private static java.util.Map<String, Object> getNestedMap(Object parent, String key) {
        if (parent instanceof java.util.Map) {
            Object value = ((java.util.Map<String, Object>) parent).get(key);
            if (value instanceof java.util.Map) {
                return (java.util.Map<String, Object>) value;
            }
        }
        return null;
    }
}
