package com.example.payload;

import jakarta.enterprise.context.ApplicationScoped;
import org.kie.api.event.process.ProcessNodeLeftEvent;
import org.kie.api.event.process.ProcessStartedEvent;
import org.kie.kogito.internal.process.event.DefaultKogitoProcessEventListener;
import org.kie.kogito.internal.process.runtime.KogitoProcessInstance;

import java.util.Map;

/**
 * Auto-generated listener that extracts payload fields from message events
 * and sets them as process variables.
 *
 * Uses appropriate event handlers based on event type:
 * - Start events: afterProcessStarted (fires after process initialization when variables are available)
 * - Catch/boundary events: afterNodeLeft (fires after node completes and data outputs are processed)
 *
 * Handles both typed payload classes and raw Map payloads.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class MessagePayloadExtractor extends DefaultKogitoProcessEventListener {

    /**
     * Handle MESSAGE START EVENTS.
     * This fires AFTER the process instance is fully initialized and message data
     * has been deserialized and placed in variables.
     */
    @Override
    public void afterProcessStarted(ProcessStartedEvent event) {
        if (event.getProcessInstance() instanceof KogitoProcessInstance) {
            KogitoProcessInstance kpi = (KogitoProcessInstance) event.getProcessInstance();
            Map<String, Object> variables = kpi.getVariables();

        // Extract fields from start event Event_1nyzw2y
        Object messageData_Event_1nyzw2y = variables.get("message_Event_1nyzw2y");
        if (messageData_Event_1nyzw2y != null) {
            if (messageData_Event_1nyzw2y instanceof com.example.payload.RenewalsPayload) {
                // Typed payload - BPMN has correct structureRef
                com.example.payload.RenewalsPayload typedPayload = (com.example.payload.RenewalsPayload) messageData_Event_1nyzw2y;
                variables.put("userId", typedPayload.getUserId());
            } else if (messageData_Event_1nyzw2y instanceof java.util.Map) {
                // Raw Map payload - navigate structure as specified in expressions
                @SuppressWarnings("unchecked")
                java.util.Map<String, Object> rawMap = (java.util.Map<String, Object>) messageData_Event_1nyzw2y;
                Object userIdValue = (rawMap.containsKey("specversion") && rawMap.containsKey("data")
                    ? (getNestedMap(rawMap, "data") != null ? getNestedMap(rawMap, "data").get("userId") : null)
                    : rawMap.get("userId"));
                if (userIdValue != null) {
                    variables.put("userId", userIdValue);
                }
            }
        }
        }
    }

    /**
     * Safely get a nested map from a parent map
     */
    @SuppressWarnings("unchecked")
    private static java.util.Map<String, Object> getNestedMap(Object parent, String key) {
        if (parent instanceof java.util.Map) {
            Object value = ((java.util.Map<String, Object>) parent).get(key);
            if (value instanceof java.util.Map) {
                return (java.util.Map<String, Object>) value;
            }
        }
        return null;
    }
}
