package com.example.payload;

import jakarta.enterprise.context.ApplicationScoped;
import org.kie.api.event.process.ProcessNodeTriggeredEvent;
import org.kie.kogito.internal.process.event.DefaultKogitoProcessEventListener;
import org.kie.kogito.internal.process.runtime.KogitoProcessInstance;
import org.kie.kogito.internal.process.runtime.KogitoWorkflowProcessInstance;

/**
 * Auto-generated listener that extracts payload fields from message events
 * and sets them as process variables.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class MessagePayloadExtractor extends DefaultKogitoProcessEventListener {

    @Override
    public void afterNodeTriggered(ProcessNodeTriggeredEvent event) {
        String nodeId = event.getNodeInstance().getNodeId().toExternalFormat();

        System.out.println(">>> MessagePayloadExtractor: afterNodeTriggered for nodeId=" + nodeId);

        if (event.getProcessInstance() instanceof KogitoWorkflowProcessInstance) {
            KogitoWorkflowProcessInstance kpi = (KogitoWorkflowProcessInstance) event.getProcessInstance();

            if ("Event_0m799to".equals(nodeId)) {
                Object msgVar = kpi.getVariable("message_Event_0m799to");
                System.out.println(">>> message_Event_0m799to = " + msgVar);

                if (msgVar instanceof RenewalsPayload) {
                    RenewalsPayload payload = (RenewalsPayload) msgVar;
                    String userId = payload.getUserId();
                    System.out.println(">>> Extracted userId from payload: " + userId);

                    // Use setVariable to properly update the process variable
                    kpi.setVariable("userId", userId);
                    System.out.println(">>> Set process variable userId = " + userId);

                    // Verify it was set
                    System.out.println(">>> Verification - kpi.getVariable(userId) = " + kpi.getVariable("userId"));
                }
            }
        }
    }
}
