package com.example.payload;

import jakarta.enterprise.context.ApplicationScoped;
import org.kie.api.event.process.ProcessEventListener;
import org.kie.kogito.process.ProcessEventListenerConfig;

import java.util.Collection;
import java.util.List;

/**
 * Configuration class to register process event listeners with Kogito.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class ProcessListenerConfig implements ProcessEventListenerConfig {

    @Override
    public Collection<ProcessEventListener> listeners() {
        System.out.println(">>> ProcessListenerConfig: Registering MessagePayloadExtractor");
        return List.of(new MessagePayloadExtractor());
    }
}
