package com.example.payload;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.quarkus.runtime.annotations.RegisterForReflection;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Auto-generated payload class for CloudEvent message data.
 * Generated by BAMOE - do not edit manually.
 */
@JsonDeserialize(using = RenewalsPayloadDeserializer.class)
@JsonIgnoreProperties(ignoreUnknown = true)
@RegisterForReflection
public class RenewalsPayload {

    private String userId;

    public RenewalsPayload() {
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
