package com.example.payload;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;

/**
 * Custom deserializer for RenewalsPayload to handle nested JSONPath expressions.
 * Handles both full CloudEvents envelope and extracted data payloads.
 * Generated by BAMOE - do not edit manually.
 */
public class RenewalsPayloadDeserializer extends JsonDeserializer<RenewalsPayload> {

    @Override
    public RenewalsPayload deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
        JsonNode root = p.getCodec().readTree(p);
        String json = root.toString();

        RenewalsPayload payload = new RenewalsPayload();

        // Handle both full CloudEvents envelope and extracted data
        if (root.has("specversion") && root.has("data")) {
            // Full CloudEvents envelope - navigate full path
            JsonNode userIdNode = root.path("data").path("userId");
            if (userIdNode != null && !userIdNode.isMissingNode()) {
                payload.setUserId(userIdNode.asText());
            }
        } else if (root.has("userId")) {
            // Data already extracted by Kogito - access directly
            payload.setUserId(root.get("userId").asText());
        }

        return payload;
    }
}
