package com.example.payload.consumer;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import io.smallrye.common.annotation.Blocking;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletionStage;

/**
 * Auto-generated Kafka message consumer for renewals.
 * Extracts payload fields and starts the renewal process with variables.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class RenewalsMessageConsumer {

    private static final Logger LOG = LoggerFactory.getLogger(RenewalsMessageConsumer.class);
    private static final ObjectMapper mapper = new ObjectMapper();

    @Inject
    org.kie.kogito.process.Processes processes;

    @Incoming("renewals")
    @Blocking
    public CompletionStage<Void> consume(Message<String> message) {
        try {
            String payload = message.getPayload();
            LOG.debug("Received message on renewals: {}", payload);

            JsonNode root = mapper.readTree(payload);
            Map<String, Object> variables = new HashMap<>();

            // Extract: $.data.userId -> userId
            JsonNode dataNode = root.path("data");
            if (!dataNode.isMissingNode()) {
                JsonNode userIdNode = dataNode.path("userId");
                if (!userIdNode.isMissingNode()) {
                    variables.put("userId", userIdNode.asText(null));
                }
            }

            LOG.info("Starting process renewal with variables: {}", variables.keySet());
            @SuppressWarnings("rawtypes")
            org.kie.kogito.process.Process process = processes.processById("renewal");
            org.kie.kogito.Model model = (org.kie.kogito.Model) process.createModel();
            model.fromMap(variables);
            ((org.kie.kogito.process.ProcessInstance<?>) process.createInstance(model)).start("renewals", null);

            return message.ack();
        } catch (Exception e) {
            LOG.error("Failed to process message on renewals", e);
            return message.nack(e);
        }
    }
}
