/**
 * Kafka Consumer Generator
 * Generates Quarkus/Smallrye Reactive Messaging consumers that intercept
 * Kafka messages and start processes with extracted variables.
 */

import { PayloadFieldDefinition, toPascalCase, toCamelCase, getJavaType } from './java-generator';

/**
 * Configuration for a Kafka consumer
 */
export interface KafkaConsumerConfig {
  messageName: string;
  processId: string;
  fields: PayloadFieldDefinition[];
  cloudEvents: boolean;
}

/**
 * Generate the consumer class name from the message name
 */
export function getConsumerClassName(messageName: string): string {
  return toPascalCase(messageName) + 'MessageConsumer';
}

/**
 * Get the channel name from the message name (preserves original case)
 */
export function getChannelName(messageName: string): string {
  return messageName;
}

/**
 * Generate the process method name from the process ID
 * Kogito generates methods like: processes.createRenewal() for process id "renewal"
 */
export function getProcessMethodName(processId: string): string {
  return 'create' + toPascalCase(processId);
}

/**
 * Generate field extraction code for a single field
 */
function generateFieldExtraction(field: PayloadFieldDefinition, cloudEvents: boolean): string {
  const fieldName = toCamelCase(field.name);
  const javaType = getJavaType(field.type);
  const expression = field.expression || `$.${fieldName}`;

  // Parse the JSONPath expression
  const pathSegments = expression
    .replace(/^\$\.?/, '')
    .split('.')
    .filter((s: string) => s);

  if (pathSegments.length === 0) {
    return `            // Extract: ${fieldName}
            if (root.has("${fieldName}")) {
                variables.put("${fieldName}", root.path("${fieldName}").${getJsonNodeAccessor(javaType)});
            }`;
  }

  if (pathSegments.length === 1) {
    const jsonField = pathSegments[0];
    return `            // Extract: $.${jsonField} -> ${fieldName}
            if (root.has("${jsonField}")) {
                variables.put("${fieldName}", root.path("${jsonField}").${getJsonNodeAccessor(javaType)});
            }`;
  }

  if (pathSegments.length === 2 && pathSegments[0] === 'data') {
    // CloudEvents format: $.data.fieldName
    const actualField = pathSegments[1];
    return `            // Extract: $.data.${actualField} -> ${fieldName}
            JsonNode dataNode = root.path("data");
            if (!dataNode.isMissingNode()) {
                JsonNode ${fieldName}Node = dataNode.path("${actualField}");
                if (!${fieldName}Node.isMissingNode()) {
                    variables.put("${fieldName}", ${fieldName}Node.${getJsonNodeAccessor(javaType)});
                }
            }`;
  }

  // General nested path
  let traversal = 'root';
  for (const segment of pathSegments) {
    traversal += `.path("${segment}")`;
  }
  return `            // Extract: ${expression} -> ${fieldName}
            JsonNode ${fieldName}Node = ${traversal};
            if (!${fieldName}Node.isMissingNode()) {
                variables.put("${fieldName}", ${fieldName}Node.${getJsonNodeAccessor(javaType)});
            }`;
}

/**
 * Get the appropriate JsonNode accessor method for a Java type
 */
function getJsonNodeAccessor(javaType: string): string {
  switch (javaType) {
    case 'String':
      return 'asText(null)';
    case 'Boolean':
      return 'asBoolean()';
    case 'Integer':
      return 'asInt()';
    case 'Long':
      return 'asLong()';
    case 'Double':
    case 'Float':
      return 'asDouble()';
    default:
      return 'asText(null)';
  }
}

/**
 * Generate a Kafka message consumer class
 */
export function generateKafkaConsumerClass(
  packageName: string,
  config: KafkaConsumerConfig
): string {
  const className = getConsumerClassName(config.messageName);
  const channelName = getChannelName(config.messageName);
  const processMethod = getProcessMethodName(config.processId);

  const fieldExtractions = config.fields
    .map(field => generateFieldExtraction(field, config.cloudEvents))
    .join('\n\n');

  return `package ${packageName};

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import io.smallrye.common.annotation.Blocking;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletionStage;

/**
 * Auto-generated Kafka message consumer for ${config.messageName}.
 * Extracts payload fields and starts the ${config.processId} process with variables.
 * Generated by BAMOE - do not edit manually.
 */
@ApplicationScoped
public class ${className} {

    private static final Logger LOG = LoggerFactory.getLogger(${className}.class);
    private static final ObjectMapper mapper = new ObjectMapper();

    @Inject
    org.kie.kogito.process.Processes processes;

    @Incoming("${channelName}")
    @Blocking
    public CompletionStage<Void> consume(Message<String> message) {
        try {
            String payload = message.getPayload();
            LOG.debug("Received message on ${channelName}: {}", payload);

            JsonNode root = mapper.readTree(payload);
            Map<String, Object> variables = new HashMap<>();

${fieldExtractions}

            LOG.info("Starting process ${config.processId} with variables: {}", variables.keySet());
            @SuppressWarnings("rawtypes")
            org.kie.kogito.process.Process process = processes.processById("${config.processId}");
            org.kie.kogito.Model model = (org.kie.kogito.Model) process.createModel();
            model.fromMap(variables);
            ((org.kie.kogito.process.ProcessInstance<?>) process.createInstance(model)).start("${channelName}", null);

            return message.ack();
        } catch (Exception e) {
            LOG.error("Failed to process message on ${channelName}", e);
            return message.nack(e);
        }
    }
}
`;
}

